import Head from 'next/head';
import styled, { css } from 'styled-components';
import { flexCol } from '../styles/templates';
import Form from '../components/Form';

export default function Home() {
  return (
    <Main>
      <Head>
        <title>RPG Character Maker</title>
        <meta
          name="RPG Character Maker"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Form />
    </Main>
  );
}

const Main = styled.main`
  background-color: ${({ theme }) => theme.background.primary};
  height: 95vh;
  width: 100vw;
  ${flexCol}
  justify-content: center;
`;



