import Head from 'next/head';
import { Main } from '../components/component.styles';
import Form from '../components/Form';

export default function Home() {
  return (
    <Main>
      <Head>
        <title>RPG Character Maker</title>
        <meta
          name="RPG Character Maker"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form />
    </Main>
  );
}
